In [83]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt

In [1]:
!nvidia-smi

Sat Jun 24 02:53:44 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.18                 Driver Version: 531.18       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070       WDDM | 00000000:08:00.0  On |                  N/A |
|  0%   58C    P3               50W / 270W|   2114MiB /  8192MiB |     36%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# <span style='color:black ' size='50'>Tensory</span>

### <span style='color:black ' size='50'>Skalarny</span>

In [8]:
#Skalarny
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

### <span style='color:black ' size='50'>Vektor</span>

In [9]:
vector = torch.tensor([1, 3])
vector

tensor([1, 3])

In [13]:
vector.ndim

1

### <span style='color:black ' size='50'>Matryca</span>

In [15]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [16]:
matrix.ndim

2

### <span style='color:black ' size='50'>Randomowe tensory</span>

In [6]:
random_tensor = torch.rand(3,3,3)
random_tensor

tensor([[[0.2209, 0.2726, 0.3291],
         [0.8909, 0.8335, 0.2135],
         [0.4172, 0.2142, 0.3592]],

        [[0.2635, 0.0239, 0.6920],
         [0.3548, 0.1151, 0.9540],
         [0.7550, 0.8017, 0.3410]],

        [[0.5658, 0.9401, 0.3630],
         [0.1132, 0.6586, 0.7873],
         [0.1706, 0.7017, 0.7500]]])

In [4]:
#obraz 256x256
random_image_tensor = torch.rand(3, 256, 256)
random_image_tensor

tensor([[[0.1862, 0.7520, 0.4320,  ..., 0.5461, 0.4416, 0.6353],
         [0.1552, 0.3442, 0.5062,  ..., 0.2222, 0.3910, 0.0276],
         [0.5893, 0.5126, 0.4871,  ..., 0.9916, 0.9317, 0.2499],
         ...,
         [0.1382, 0.7348, 0.7144,  ..., 0.7222, 0.6239, 0.8184],
         [0.6936, 0.0467, 0.1469,  ..., 0.0320, 0.8939, 0.2147],
         [0.0965, 0.3339, 0.3700,  ..., 0.5270, 0.3162, 0.3604]],

        [[0.5977, 0.1610, 0.4992,  ..., 0.5961, 0.1828, 0.0780],
         [0.5214, 0.8844, 0.7324,  ..., 0.1144, 0.1508, 0.2853],
         [0.0969, 0.0613, 0.4879,  ..., 0.2010, 0.1825, 0.4187],
         ...,
         [0.1799, 0.9309, 0.4100,  ..., 0.3205, 0.3876, 0.4542],
         [0.7733, 0.5536, 0.7058,  ..., 0.8859, 0.6769, 0.1050],
         [0.6243, 0.4450, 0.9412,  ..., 0.6814, 0.4957, 0.8920]],

        [[0.0222, 0.5046, 0.6308,  ..., 0.2729, 0.5574, 0.7624],
         [0.2754, 0.6516, 0.8685,  ..., 0.0702, 0.7225, 0.9108],
         [0.4496, 0.2380, 0.4072,  ..., 0.4967, 0.8194, 0.

In [7]:
random_tensor.dtype

torch.float32

### <span style='color:black ' size='50'>Tensory w zakresie</span>

In [14]:
tensor_range = torch.arange(0,10,2)
tensor_range

tensor([0, 2, 4, 6, 8])

In [13]:
#podobny array
alike = torch.zeros_like(tensor_range)
alike

tensor([0, 0, 0, 0, 0])

# <span style='color:black ' size='50'>Typy danych</span>

In [24]:
float_32_tensor = torch.tensor([1.,2.,3.,4.,5.],
                               dtype=None, #float32, float16, float64
                               device=None, #'cuda' or 'cpu'
                               requires_grad=False) #Czy śledzić gradient?
float_32_tensor.dtype

torch.float32

In [19]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

In [25]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

In [26]:
float_16_tensor*float_64_tensor

tensor([ 1.,  4.,  9., 16., 25.], dtype=torch.float64)

# <span style='color:black ' size='50'>Operacje na tensorach</span>

In [27]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
tensor*2

tensor([2, 4, 6])

In [30]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [32]:
tensor*2

tensor([2, 4, 6])

In [33]:
#Mnożenie matryc
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0194, 0.7340],
        [0.6225, 0.4586]])

In [36]:
torch.matmul(torch.rand(2,3), torch.rand(2,3).T)

tensor([[0.8142, 1.6575],
        [0.7362, 1.6281]])

### <span style='color:black ' size='50'>Agregacja tensorowa</span>

In [42]:
x = torch.arange(1,101,7)
x

tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
        99.], dtype=torch.float16)

In [38]:
torch.max(x)

tensor(99)

In [39]:
torch.min(x)

tensor(1)

In [45]:
torch.mean(x.type(torch.float16))

tensor(50., dtype=torch.float16)

In [46]:
torch.sum(x)

tensor(750., dtype=torch.float16)

In [48]:
#Index min i max
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(14)

### <span style='color:black ' size='50'>Modyfikacja tensorów</span>

In [56]:
#zmiana kształtu
x.resize(5,3)

tensor([[ 1.,  8., 15.],
        [22., 29., 36.],
        [43., 50., 57.],
        [64., 71., 78.],
        [85., 92., 99.]], dtype=torch.float16)

In [60]:
#Łączenie tensorów
torch.stack([x, x, x, x], dim=1)

tensor([[ 1.,  1.,  1.,  1.],
        [ 8.,  8.,  8.,  8.],
        [15., 15., 15., 15.],
        [22., 22., 22., 22.],
        [29., 29., 29., 29.],
        [36., 36., 36., 36.],
        [43., 43., 43., 43.],
        [50., 50., 50., 50.],
        [57., 57., 57., 57.],
        [64., 64., 64., 64.],
        [71., 71., 71., 71.],
        [78., 78., 78., 78.],
        [85., 85., 85., 85.],
        [92., 92., 92., 92.],
        [99., 99., 99., 99.]], dtype=torch.float16)

In [64]:
x.reshape(1, 15).shape

torch.Size([1, 15])

In [69]:
x.reshape(1, 15).squeeze().shape

torch.Size([15])

In [74]:
x.reshape(1, 15).unsqueeze(2).shape

torch.Size([1, 15, 1])

In [78]:
#Permutacja
x = torch.rand(1,2,3)
x.size()

torch.Size([1, 2, 3])

In [80]:
torch.permute(x, (2,1,0)).shape

torch.Size([3, 2, 1])

# <span style='color:black ' size='50'>Seedy</span>

In [82]:
a = torch.rand(2,2)
b = torch.rand(2,2)
a == b

tensor([[False, False],
        [False, False]])

In [86]:
torch.manual_seed(42)
c = torch.rand(2,2)
torch.manual_seed(42)
d = torch.rand(2,2)
c == d

tensor([[True, True],
        [True, True]])

# <span style='color:black ' size='50'>Korzystanie z GPU</span>

In [88]:
torch.cuda.is_available()

True

In [89]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [90]:
torch.cuda.device_count()

1

In [92]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [93]:
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

In [96]:
tensor.cpu().device

device(type='cpu')